# Generated by Django 4.1.7 on 2023-03-21 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_athlete_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефону у форматі: '+380999999'. Дозволено до 13 цифр.",
                        regex="^\\+?1?\\d{9,13}$",
                    )
                ],
                verbose_name="Номер телефону",
            ),
        ),
    ]
