# Generated by Django 4.1.7 on 2023-03-28 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_athlete_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="athlete",
            options={
                "ordering": ("username",),
                "verbose_name": "Athlete",
                "verbose_name_plural": "Athletes",
            },
        ),
        migrations.AlterField(
            model_name="athlete",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Населений пункт"
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="club",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Спортивний клуб"
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Ім'я екстреного контакту",
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Номер телефону екстреного контакту",
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=6,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефону у форматі: '+380999999'. Дозволено до 13 цифр.",
                        regex="^\\+?1?\\d{9,13}$",
                    )
                ],
                verbose_name="Номер телефону",
            ),
        ),
    ]
