# Generated by Django 4.1.7 on 2023-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_athlete_options_alter_athlete_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=6,
                verbose_name="Стать",
            ),
        ),
    ]
