# Generated by Django 4.1.7 on 2023-03-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_athlete_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                choices=[("male", "Чоловіча"), ("female", "Жіноча")],
                default="male",
                max_length=6,
                verbose_name="Стать",
            ),
        ),
    ]
