# Generated by Django 4.1.7 on 2023-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpages", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpage",
            name="url",
            field=models.CharField(
                help_text="Only latin characters",
                max_length=20,
                unique=True,
                verbose_name="URL-name",
            ),
        ),
    ]
