# Generated by Django 4.1.7 on 2023-03-16 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sportevent.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Назва")),
                (
                    "distance_in_unit",
                    models.PositiveSmallIntegerField(verbose_name="Дистанція"),
                ),
            ],
            options={
                "verbose_name": "Дистанція",
                "verbose_name_plural": "Дистанції",
                "ordering": ("-event",),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Назва")),
                ("date_event", models.DateField(verbose_name="Дата проведення")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Місце проведення"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="Завантажити зображення: (PNG, JPEG, JPG)",
                        null=True,
                        upload_to=sportevent.models.Event.generate_path,
                        verbose_name="Постер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спортивний захід",
                "verbose_name_plural": "Спортивні заходи",
                "ordering": ("-date_event",),
            },
        ),
        migrations.CreateModel(
            name="ResultEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                ("result_time", models.TimeField(verbose_name="Результат")),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sportevent.event",
                        verbose_name="Захід",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результати заходу",
                "verbose_name_plural": "Результати заходів",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RegisterDistanceAthlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "start_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Номер учасника",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_distance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Атлети",
                    ),
                ),
                (
                    "distance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_distance",
                        to="sportevent.distance",
                        verbose_name="Дистанція",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атлета на дистанцію",
                "verbose_name_plural": "Зареєстровані атлети на дистанції",
                "ordering": ("start_number",),
            },
        ),
        migrations.AddField(
            model_name="distance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distances",
                to="sportevent.event",
                verbose_name="Спорт захід",
            ),
        ),
    ]
