# Generated by Django 4.1.7 on 2023-03-21 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distance",
            options={
                "ordering": ("-distance_in_unit",),
                "verbose_name": "Дистанція",
                "verbose_name_plural": "Дистанції",
            },
        ),
    ]
