# Generated by Django 4.1.7 on 2023-03-04 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distance",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Дистанція",
                "verbose_name_plural": "Дистанції",
            },
        ),
        migrations.CreateModel(
            name="ResultEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                ("result_time", models.TimeField(verbose_name="Результат")),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sportevent.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результати заходу",
                "verbose_name_plural": "Результати заходи",
                "ordering": ("-created_at",),
            },
        ),
    ]
