# Generated by Django 4.1.7 on 2023-03-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sportevent.models


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0002_alter_distance_options_resultevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resultevent",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Результати заходу",
                "verbose_name_plural": "Результати заходів",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="poster",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Завантажити зображення: (PNG, JPEG, JPG)",
                null=True,
                upload_to=sportevent.models.Event.generate_path,
                verbose_name="Постер",
            ),
        ),
        migrations.AlterField(
            model_name="distance",
            name="athlete",
            field=models.ManyToManyField(
                blank=True,
                related_name="athletes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Атлети",
            ),
        ),
        migrations.AlterField(
            model_name="distance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="sportevent.event",
                verbose_name="Спорт захід",
            ),
        ),
        migrations.AlterField(
            model_name="resultevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sportevent.event",
                verbose_name="Захід",
            ),
        ),
    ]
