# Generated by Django 4.1.7 on 2023-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0002_alter_distance_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerdistanceathlete",
            name="start_number",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Номер учасника"
            ),
        ),
    ]
