# Generated by Django 4.1.7 on 2023-03-09 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0003_alter_resultevent_options_event_poster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distance",
            name="athlete",
            field=models.ManyToManyField(
                blank=True,
                related_name="distances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Атлети",
            ),
        ),
        migrations.AlterField(
            model_name="distance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distances",
                to="sportevent.event",
                verbose_name="Спорт захід",
            ),
        ),
    ]
