# Generated by Django 4.1.7 on 2023-03-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0003_alter_registerdistanceathlete_start_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultevent",
            name="event",
        ),
        migrations.AddField(
            model_name="resultevent",
            name="distance",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="sportevent.distance",
                verbose_name="Дистанція",
            ),
        ),
    ]
