# Generated by Django 4.1.7 on 2023-03-10 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0004_alter_distance_athlete_alter_distance_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("-date_event",),
                "verbose_name": "Спортивний захід",
                "verbose_name_plural": "Спортивні заходи",
            },
        ),
        migrations.RemoveField(
            model_name="distance",
            name="athlete",
        ),
        migrations.CreateModel(
            name="RegisterDistanceAthlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "start_number",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Номер учасника"
                    ),
                ),
                (
                    "athlete",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registered_distance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Атлети",
                    ),
                ),
                (
                    "distance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sportevent.distance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зареєструвати атлета на дистанцію",
                "verbose_name_plural": "Зареєстровані атлети на дистанції",
                "ordering": ("start_number",),
            },
        ),
    ]
