# Generated by Django 4.1.7 on 2023-03-25 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sportevent", "0004_remove_resultevent_event_resultevent_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultevent",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Атлет",
            ),
        ),
        migrations.AlterField(
            model_name="resultevent",
            name="distance",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="sportevent.distance",
                verbose_name="Дистанція",
            ),
        ),
    ]
