# Generated by Django 4.1.7 on 2023-03-10 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0005_alter_event_options_remove_distance_athlete_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distance",
            options={
                "ordering": ("-event",),
                "verbose_name": "Дистанція",
                "verbose_name_plural": "Дистанції",
            },
        ),
        migrations.RemoveField(
            model_name="registerdistanceathlete",
            name="athlete",
        ),
        migrations.AlterField(
            model_name="registerdistanceathlete",
            name="distance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_distance",
                to="sportevent.distance",
            ),
        ),
        migrations.AddField(
            model_name="registerdistanceathlete",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_distance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
