# Generated by Django 4.1.7 on 2023-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0006_alter_distance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerdistanceathlete",
            name="start_number",
            field=models.PositiveSmallIntegerField(
                default=1, unique=True, verbose_name="Номер учасника"
            ),
        ),
    ]
