# Generated by Django 4.1.7 on 2023-03-28 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0006_remove_resultevent_distance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resultevent",
            options={
                "ordering": ("result_time",),
                "verbose_name": "Результат атлета на дистанції",
                "verbose_name_plural": "Результати атлетів на дистанції",
            },
        ),
    ]
