# Generated by Django 4.1.7 on 2023-03-30 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0007_alter_resultevent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resultevent",
            options={
                "ordering": ("-result_time",),
                "verbose_name": "Результат атлета на дистанції",
                "verbose_name_plural": "Результати атлетів на дистанції",
            },
        ),
    ]
