# Generated by Django 4.1.7 on 2023-03-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0008_alter_registerdistanceathlete_start_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registerdistanceathlete",
            options={
                "ordering": ("start_number",),
                "verbose_name": "Атлета на дистанцію",
                "verbose_name_plural": "Зареєстровані атлети на дистанції",
            },
        ),
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                choices=[("male", "Чоловіча"), ("female", "Жіноча")],
                max_length=10,
                null=True,
                verbose_name="Стать",
            ),
        ),
        migrations.AlterField(
            model_name="registerdistanceathlete",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_distance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Атлети",
            ),
        ),
        migrations.AlterField(
            model_name="registerdistanceathlete",
            name="distance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_distance",
                to="sportevent.distance",
                verbose_name="Дистанція",
            ),
        ),
    ]
