# Generated by Django 4.1.7 on 2023-04-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0008_alter_resultevent_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultevent",
            name="athlete",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results",
                to="sportevent.registerdistanceathlete",
                verbose_name="Атлет",
            ),
        ),
    ]
