# Generated by Django 4.1.7 on 2023-04-11 20:05

import datetime
from django.db import migrations, models
import sportevent.service


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0010_event_registration_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="distance",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="distance",
            name="road_map",
            field=models.TextField(blank=True, null=True, verbose_name="Road map"),
        ),
        migrations.AddField(
            model_name="distance",
            name="road_map_image",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Download image: (PNG, JPEG, JPG)",
                null=True,
                upload_to=sportevent.service.generate_path,
                verbose_name="Road map image",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 23, 5, 25, 910848),
                help_text="Enter the end date of registration for the event",
                verbose_name="Registration end date",
            ),
        ),
    ]
