# Generated by Django 4.1.7 on 2023-03-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0010_alter_athlete_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Чоловіча"), ("female", "Жіноча")],
                max_length=10,
                verbose_name="Стать",
            ),
        ),
    ]
