# Generated by Django 4.1.7 on 2023-04-11 20:44

import datetime
from django.db import migrations, models
import sportevent.service


class Migration(migrations.Migration):
    dependencies = [
        ("sportevent", "0011_distance_description_distance_road_map_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distance",
            name="road_map_image",
            field=models.ImageField(
                blank=True,
                help_text="Download image: (PNG, JPEG, JPG)",
                null=True,
                upload_to=sportevent.service.generate_path,
                verbose_name="Road map image",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 23, 44, 36, 525770),
                help_text="Enter the end date of registration for the event",
                verbose_name="Registration end date",
            ),
        ),
    ]
